//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public string MaPH { get; set; }
        public string MaKM { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string ThucAn { get; set; }
        public string MaLoai { get; set; }
        public string NgayLap { get; set; }
        public string ThangLap { get; set; }
        public string NamLap { get; set; }
    
        public virtual PhongHat PhongHat { get; set; }
    }
}
