//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string MaKM { get; set; }
        public string TenKM { get; set; }
        public string Noidung { get; set; }
        public Nullable<double> GiaKM { get; set; }
        public Nullable<double> GiaHT { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
