//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanPhong
    {
        public string MaNP { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public string GioNhan { get; set; }
        public string MaPH { get; set; }
        public Nullable<int> SoLuongNguoi { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
    
        public virtual PhongHat PhongHat { get; set; }
    }
}
