//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string MaNV { get; set; }
        public string TenDN { get; set; }
        public string MatMaDN { get; set; }
        public string QuyenDN { get; set; }
        public string HoTenNV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public bool Phai { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<double> LuongNV { get; set; }
    }
}
