//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatPhong
    {
        public string SoPD { get; set; }
        public System.DateTime NgayDat { get; set; }
        public string GioDat { get; set; }
        public string BuoiDat { get; set; }
        public Nullable<double> TienDatCoc { get; set; }
        public string MaPH { get; set; }
        public string MaKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhongHat PhongHat { get; set; }
    }
}
