//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBi()
        {
            this.CTThietBi = new HashSet<CTThietBi>();
        }
    
        public string MaTB { get; set; }
        public string TenTB { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MaLoaiTB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTThietBi> CTThietBi { get; set; }
        public virtual LoaiThietBi LoaiThietBi { get; set; }
    }
}
