//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public string MaTB { get; set; }
        public string NguoiGui { get; set; }
        public string NguoiNhan { get; set; }
        public Nullable<System.DateTime> Ngaygui { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public string NoiDungTB { get; set; }
        public Nullable<bool> TrangThaiTB { get; set; }
    }
}
